DROP DATABASE IF EXISTS `codeverse`;

CREATE DATABASE `codeverse`;

USE `codeverse`;

CREATE TABLE `login` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NULL,
);

